name: PR Check

on:
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 24 # @NOTE Should match .nvmrc

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Install Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Validate package version numbers
        run: node scripts/validate-versions.js

      - name: Lint, test, and build
        run: npm run checkall

  # @TODO Move to `release.yml`
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: Install Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build static files
        id: build
        run: npm run docs

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4



